#!/bin/bash
r=`curl https://openeyes.moorfields.nhs.uk/site/login 2>/dev/null |grep '<title>OpenEyes - Login</title>'`
if [ "$r" == "" ] ; then
	echo "BAD: Couldn't load the login page"
	exit 2
fi
echo "OK: Login page loaded"
exit 0
