#!/bin/bash
pid=`cat /opt/blackbox/blackbox.pid`
if [ "$pid" == "" ] ; then
	echo "BAD: Not running (no pid)"
	exit 2
fi
r=`ps -p $pid |xargs -L1 |egrep -v '^PID TTY'`
if [ "$r" == "" ] ; then
	echo "BAD: Not running"
	exit 2
fi
echo "OK: running as pid $pid"
exit 0
