#!/bin/bash
r=`ls -la /opt/blackbox/incoming/*.tif |wc -l`
if [[ $r -gt 150 ]] ; then
	echo "CRITICAL: $r incoming"
	exit 2
fi
if [[ $r -gt 100 ]] ; then
	echo "WARNING: $r incoming"
	exit 1
fi
echo "OK: $r incoming"
exit 0
