#!/bin/bash
lockfile="/root/backup_rsync.lock"
trap "[ -f $lockfile ] && /bin/rm -f $lockfile" 2 3 13 15
lockfile -r 0 $lockfile || exit 1
hostname=`hostname`
rsync -aPr /backup/$hostname/ /mehbackup/$hostname/ 1>/dev/null 2>/root/backup_rsync.output
r=`cat /root/backup_rsync.output`
if [ ! "$r" == "" ] ; then
	cat /root/backup_rsync.output >> /root/backup_rsync.log
	echo 0 > /etc/nagios/backup.status
else
	echo 1 > /etc/nagios/backup.status
fi
